### ISSUE TITLE
devops: frontend deployment

### ISSUE THREAD

**Issue by yjkimjunior** [paritytech/Nomidot#344]
cc @fevo1971 

Could we please get the frontend into continuous deployment as done in Polkassembly?

There is a `front/kubernetes` https://github.com/paritytech/Nomidot/tree/master/front/kubernetes/staging folder but this deployment and service were removed in favor of Netlify, but given https://github.com/paritytech/Nomidot/pull/263#issuecomment-604923989, we'd need to return to the original.

**Comment by fevo1971** [comment]
two questions: 

1. reading the [deployment.yaml](https://github.com/paritytech/Nomidot/blob/master/front/kubernetes/staging/frontend-deployment.yaml) & looking at the [repo](https://github.com/paritytech/Nomidot/tree/master/front/kubernetes/staging) i can't see any kind of configuration. but guess there must be at least some kind of configuration about where to find the backend, rigth? 

2. is there a url (host and domainname) that we need to point to the frontend once it's deployed? if so then what will it be?

**Comment by yjkimjunior** [comment]
1. It is specified here, but we'd need to specify `NODE_ENV` in the `deployment.yaml` https://github.com/paritytech/Nomidot/blob/b20de78af0841c5516b31de92e8c5e4ae8c6e694/front/gatsby/src/apollo.ts#L12. Note, that is fixed here: https://github.com/paritytech/Nomidot/pull/345/files

2. So this would just be a 'staging' deployment for now, we haven't got a domain name yet, so could we perhaps get something under test-installtions like `test-installations.nomi.com`?

**Comment by fevo1971** [comment]
i just did a 1st test deployment of the frontend into the *dashboards-cluster-1* using the new namspace *nomidot-kusama*. and get the following error when starting the (latest) [nomidot-frontend](https://hub.docker.com/layers/paritytech/nomidot-frontend/master-b20de78a/images/sha256-07d8908b3c04521d6c858e392619ba8f8904675f246530cf7dfed6c855fa3d1b?context=explore) container:

```
ERROR #98123  WEBPACK

Generating JavaScript bundles failed

Can't resolve 'rxjs/operators' in '/context/src'

File: ../context/src/AccountsContext.tsx


 ERROR #98123  WEBPACK

Generating JavaScript bundles failed

/gatsby/node_modules/gatsby/dist/utils/babel-loader.js??ref--4-0!/gatsby/gatsby-browser.js 1c87fd3332edb05a5655d6e4dc52b470
Unexpected token (5:20)
| // This software may be modified and distributed under the terms
| // of the Apache-2.0 license. See the LICENSE file for details.
| var WS_PROVIDER=new !(function webpackMissingModule() { var e = new Error("Cannot find module '@polkadot/api'"); e.code = 'MODULE_NOT_FOUND'; throw e; }())('wss://cc3-5.kusama.network/');var wrapRootElement=function wrapRootElement(_ref){var element=_ref.element;return/*#__PURE__*/__WEBPACK_MODULE_REFERENCE__4_64656661756c74__.createElement(__WEBPACK_MODULE_REFERENCE__1_41706f6c6c6f50726f7669646572__,{client:__WEBPACK_MODULE_REFERENCE__48_64656661756c74__},/*#__PURE__*/__WEBPACK_MODULE_REFERENCE__4_64656661756c74__.createElement(__WEBPACK_MODULE_REFERENCE__2_4170695278436f6e7465787450726f7669646572__,{provider:WS_PROVIDER},/*#__PURE__*/__WEBPACK_MODULE_REFERENCE__4_64656661756c74__.createElement(__WEBPACK_MODULE_REFERENCE__2_53797374656d436f6e7465787450726f7669646572__,{provider:WS_PROVIDER},/*#__PURE__*/__WEBPACK_MODULE_REFERENCE__4_64656661756c74__.createElement(__WEBPACK_MODULE_REFERENCE__2_53797374656d436f6e74657874__.Consumer,null,function(isSystemReady){return isSystemReady&&/*#__PURE__*/__WEBPACK_MODULE_REFERENCE__4_64656661756c74__.createElement(__WEBPACK_MODULE_REFERENCE__2_4163636f756e7473436f6e7465787450726f7669646572__,{originName:__WEBPACK_MODULE_REFERENCE__50_4150505f534c5547__},/*#__PURE__*/__WEBPACK_MODULE_REFERENCE__4_64656661756c74__.createElement(__WEBPACK_MODULE_REFERENCE__2_54785175657565436f6e7465787450726f7669646572__,null,element));}))));};var wrapPageElement=function wrapPageElement(_ref2){var element=_ref2.element,props=_ref2.props;return/*#__PURE__*/__WEBPACK_MODULE_REFERENCE__4_64656661756c74__.createElement(__WEBPACK_MODULE_REFERENCE__5_5468656d6550726f7669646572__,{theme:__WEBPACK_MODULE_REFERENCE__3_706f6c6b61646f744f6666696369616c5468656d65__},/*#__PURE__*/__WEBPACK_MODULE_REFERENCE__4_64656661756c74__.createElement(__WEBPACK_MODULE_REFERENCE__49_4c61796f7574__,props,/*#__PURE__*/__WEBPACK_MODULE_REFERENCE__4_64656661756c74__.createElement(__WEBPACK_MODULE_REFERENCE__49_53656f__,{title:"Polkadot/Kusama Staking Portal"}),/*#__PURE__*/__WEBPACK_MODULE_REFERENCE__4_64656661756c74__.createElement(__WEBPACK_MODULE_REFERENCE__3_476c6f62616c5374796c65__,null),/*#__PURE__*/__WEBPACK_MODULE_REFERENCE__4_64656661756c74__.createElement(__WEBPACK_MODULE_REFERENCE__49_537461747573__,null),element));};

not finished run queries - 83.453s
```


here my deployment:

```
---
# Source: nomidot/templates/frontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nomidot-frontend
  labels:
    chart: nomidot-0.1.0
    version: "1.16.0"
    managed-by: Helm
    part-of: nomidot
    app: frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: frontend
---
# Source: nomidot/templates/frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nomidot-frontend
  labels:
    chart: nomidot-0.1.0
    version: "1.16.0"
    managed-by: Helm
    part-of: nomidot
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: nomidot-frontend
          image: 'paritytech/nomidot-frontend:master-b20de78a'
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: NODE_ENV
              value: http://nodewatcher-service.nodewatcher-kusama:4466
```
